import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../build-data.mjs',import.meta.url),'utf8'),cut=(a,b)=>{const i=src.indexOf(a),j=src.indexOf(b,i);assert.ok(i>=0&&j>i);return src.slice(i,j);};
const url='https://www.aemet.es/es/eltiempo/prediccion/avisos?l=610404&w=hoy';
function setup(){const c=vm.createContext({Buffer,TextDecoder,AEMET_ZONE_CODES:{610404:{zone:'Levante almeriense'}},AEMET_ZONE_NAMES:['Levante almeriense','Poniente y Almería Capital'],AEMET_PHENOMENA:['Tormentas','Lluvias']});vm.runInContext(cut('function stripHTML(','/* ===== datos v91.9'),c);vm.runInContext(cut('function aemetDayFromURL(','function xmlBlocks('),c);vm.runInContext(cut('function sanitizeURLForLog(','function aemetAgeMinutes('),c);return c;}
test('general special-warning link and page navigation do not create local warnings',()=>{const c=setup();const html='<nav>Avisos meteorológicos Subir a la cabecera</nav><a>Aviso especial. Chubascos y tormentas muy fuertes y persistentes.</a><h3>Detalle de avisos</h3><p>Enlaces relacionados: Meteoalarm: Servicio de alerta</p>';for(const day of ['hoy','mna','pmna']){const out=c.parseAemetHTML(html,url.replace('w=hoy','w='+day));assert.equal(out.items.length,0);assert.equal(out.method,'html_unparsed');assert.equal(out.fallback_used,true);}});
test('structured table preserves verified local phenomenon, colour, period and quantity',()=>{const c=setup(),out=c.parseAemetHTML('<table><tr><td>Levante almeriense</td><td>Lluvias</td><td>amarillo</td><td>14:00–20:00</td><td>Precipitación 20 mm</td></tr></table>',url);assert.equal(out.items.length,1);assert.equal(out.items[0].period,'14:00–20:00');assert.equal(out.items[0].value,'20 mm');assert.equal(out.items[0].source_method,'html_table');});
test('table containing a general heading or missing validity is not sufficient',()=>{const c=setup();for(const cells of ['<td>Tormentas</td><td>Aviso especial</td>','<td>Tormentas</td><td>amarillo</td>','<td>Tormentas</td><td>amarillo 14:00–20:00 Subir a la cabecera</td>'])assert.equal(c.parseAemetHTML('<tr>'+cells+'</tr>',url).items.length,0);});
test('response encoding respects ISO-8859-15 header, HTML declaration, and UTF-8 default',()=>{const c=setup(),text='Avisos meteorológicos y precipitación';assert.equal(c.decodeAemetText756(Buffer.from(text,'latin1'),'text/html; charset=ISO-8859-15'),text);const html='<meta charset="iso-8859-1"><p>'+text+'</p>';assert.equal(c.decodeAemetText756(Buffer.from(html,'latin1')),html);assert.equal(c.decodeAemetText756(Buffer.from(text,'utf8')),text);});
test('old corrupted fallback cache is discarded while CAP records remain',()=>{const c=setup();const valid={source_method:'opendata_cap',phenomenon:'Lluvias',color:'amarillo',period:'14:00–20:00',comment:'Precipitación: 20 mm'};const rec=c.sanitizeAemetRecord({method:'html_fallback',html_fallback_used:true,items:[{phenomenon:'Tormentas',comment:'Avisos Avisos meteorol�gicos'},valid]},{cached:true,cacheAgeMinutes:5});assert.equal(rec.items.length,1);assert.equal(rec.items[0].comment,valid.comment);assert.equal(rec.ok,false);assert.equal(rec.cached,true);});
