import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const source=readFileSync(fileURLToPath(new URL('../build-data.mjs',import.meta.url)),'utf8');
function grabFn(name){const start=source.indexOf('function '+name+'(');if(start<0)throw new Error('falta '+name);let i=source.indexOf('{',start),d=0;for(;i<source.length;i++){if(source[i]==='{')d++;else if(source[i]==='}'&&--d===0)break;}return source.slice(start,i+1);}
function grabConst(name){const m=new RegExp('const '+name+' = [^;]+;').exec(source);if(!m)throw new Error('falta '+name);return m[0];}
const helpers='function avg(a){const v=(a||[]).filter(x=>Number.isFinite(Number(x))).map(Number);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null;}function meanDir(a){const v=(a||[]).filter(x=>Number.isFinite(Number(x))).map(Number);if(!v.length)return null;const r=v.map(x=>x*Math.PI/180),x=r.reduce((s,n)=>s+Math.cos(n),0),y=r.reduce((s,n)=>s+Math.sin(n),0);return (Math.atan2(y,x)*180/Math.PI+360)%360;}';
const api=new Function(helpers+grabConst('MARINE_BEST_SUFFIX')+grabConst('MARINE_COMPARE_SUFFIXES')+grabFn('marineSeries')+grabFn('marineMembers')+grabFn('aggregateWaveModels')+grabFn('normalizeMarineResponse')+'return {normalizeMarineResponse,aggregateWaveModels};')();
const marine={current:{sea_surface_temperature:25},hourly:{time:['2026-08-10T12:00','2026-08-10T13:00'],wave_height_marine_best_match:[0.3,0.4],wave_direction_marine_best_match:[80,85],wave_period_marine_best_match:[5,5.5],sea_surface_temperature_marine_best_match:[25,25],wave_height_meteofrance_wave:[0.2,0.3],wave_direction_meteofrance_wave:[60,70],wave_period_meteofrance_wave:[4,4.5],wave_height_dwd_ewam:[0.4,0.5],wave_direction_dwd_ewam:[100,110],wave_period_dwd_ewam:[6,6.5],wave_height_ecmwf_wam:[0.3,0.4],wave_direction_ecmwf_wam:[80,90],wave_period_ecmwf_wam:[5,5.5]},daily:{time:['2026-08-10'],wave_height_max_marine_best_match:[0.35],wave_direction_dominant_marine_best_match:[82],wave_height_max_meteofrance_wave:[0.25],wave_direction_dominant_meteofrance_wave:[65],wave_height_max_dwd_ewam:[0.45],wave_direction_dominant_dwd_ewam:[105],wave_height_max_ecmwf_wam:[0.35],wave_direction_dominant_ecmwf_wam:[85]}};
test('v91.376 datos: best_match sigue central y cada modelo conserva altura, direccion y periodo',()=>{const n=api.normalizeMarineResponse(marine);assert.equal(n.hourly.wave_height[0],0.3);assert.equal(n.hourly.wave_period[0],5);assert.deepEqual(n.hourly.wave_models[0],[{m:'meteofrance_wave',h:0.2,d:60,p:4},{m:'dwd_ewam',h:0.4,d:100,p:6},{m:'ecmwf_wam',h:0.3,d:80,p:5}]);assert.deepEqual(n.daily.wave_models[0],[{m:'meteofrance_wave',h:0.25,d:65},{m:'dwd_ewam',h:0.45,d:105},{m:'ecmwf_wam',h:0.35,d:85}]);});
test('v91.376 datos: el agregado de tramo conserva pares y no mezcla una altura con otra direccion',()=>{const n=api.normalizeMarineResponse(marine),rows=n.hourly.time.map((_,i)=>({waveModels:n.hourly.wave_models[i]})),a=api.aggregateWaveModels(rows);assert.deepEqual(a,[{m:'meteofrance_wave',h:0.25,d:65,p:4.3},{m:'dwd_ewam',h:0.45,d:105,p:6.3},{m:'ecmwf_wam',h:0.35,d:85,p:5.3}]);});
test('v91.376 datos: el contrato oficial conserva estado, fuente y hora propias',()=>{assert.match(source,/ASPPLAOLEAMODE:'moderado'/);assert.match(source,/rec.oseaSource=JUNTA_ATTR;rec.oseaAt=checkedAt/);assert.match(source,/oflag:bd.oflag||null,osea:bd.osea||null/);});
test('v91.376 datos: una sola peticion y salida horaria compacta',()=>{assert.match(source,/models=\${MARINE_MODELS}/);assert.ok(source.includes('waveModels:aggregateWaveModels(src)'));assert.ok(source.includes('miembros se publican solo por dia/tramo'));assert.doesNotMatch(source,/const hourly={[^;]*waveModels/);});
